### ISSUE TITLE
Spurious sigmoidal contrast output error

### ISSUE THREAD

**Issue by sgillies** [mapbox/rio-color#34]
I'm getting a confusing error the file at https://www.dropbox.com/s/e86y9xl1u49vjxa/moab8_crop.tif?dl=0.

```bash
$ rio atmos moab8_crop.tif moab8_cor.tif
/Users/sean/code/rasterio/rasterio/__init__.py:193: UserWarning: Dataset has no geotransform set.  Default transform will be applied (Affine.identity())
  s.start()
/Users/sean/code/rasterio/rasterio/__init__.py:193: UserWarning: Dataset uses default geotransform (Affine.identity). No transform will be written to the output by GDAL.
  s.start()
Traceback (most recent call last):
  File "/Users/sean/envs/pydotorg35/bin/rio", line 9, in <module>
    load_entry_point('rasterio==0.35.1', 'console_scripts', 'rio')()
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/rio_color/scripts/cli.py", line 178, in atmos
    arr = atmos_worker(rasters, window, ij, args)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/rio_color/workers.py", line 15, in atmos_worker
    args['bias'])
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/rio_color/operations.py", line 170, in simple_atmo
    output = sigmoidal(arr, contrast, bias)
  File "/Users/sean/envs/pydotorg35/lib/python3.5/site-packages/rio_color/operations.py", line 82, in sigmoidal
    raise ValueError("Sigmoidal contrast output is not within the range of [0,1]")
ValueError: Sigmoidal contrast output is not within the range of [0,1]
```

To see what the equivalent rio-color is, I used the `--as-color` option.

```bash
$ rio atmos --as-color moab8_crop.tif moab8_cor.tif
rio color moab8_crop.tiff moab8_cor.tif gamma g 0.99, gamma b 0.97, sigmoidal rgb 10.0 0.15
```

And then this rio-color command worked, no error.

**Comment by perrygeo** [comment]
`rio atmos` was not set up to properly handle RGBA data. The 4th band (alpha) gets set to a value beyond the 0..1 domain of the sigmoidal contrast function. The correct behavior should be to just retain the alpha band as is and perform the contrast on rgb (as rio color does). PR coming shortly.
