### ISSUE TITLE
Error in rio color command line

### ISSUE THREAD

**Issue by firmanhadi** [mapbox/rio-color#46]
Hi,
I use Mac and installed rio color as explained.
I could not execute rio color command as in the example. 

Error: no such option: -d

**Comment by perrygeo** [comment]
Can you give provide the command you entered and the full output please?

I suspect an installation problem. Can you try `rio color --help` and confirm that you see the usage page?

**Comment by firmanhadi** [comment]
This is the result: 

Firmans-MacBook-Pro:Phillipines firmanhadi$ rio color --help
Usage: rio color [OPTIONS]

  Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "/Library/Python/2.7/site-packages/click_plugins/core.py", line 37, in decorator
      group.add_command(entry_point.load())
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
      entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    File "/Library/Python/2.7/site-packages/rio_color/scripts/cli.py", line 5, in <module>
      from rio_color.workers import atmos_worker, color_worker
    File "/Library/Python/2.7/site-packages/rio_color/workers.py", line 1, in <module>
      from .operations import parse_operations, simple_atmo
    File "/Library/Python/2.7/site-packages/rio_color/operations.py", line 3, in <module>
      from .colorspace import saturate_rgb
    File "release/venv35/lib/python3.5/site-packages/Cython/Includes/numpy/__init__.pxd", line 155, in init rio_color.colorspace (rio_color/colorspace.c:7498)
  ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96

Options:
  --help  Show this message and exit.

**Comment by perrygeo** [comment]
Thanks @firmanhadi - sounds like a installation problem. Specifically it looks like some packages are being installed to the system Python 2.7 and others (numpy) from the Python 3.5 venv. Mixing C extension modules compiled for different versions of Python will not work.

I'm not sure about the specifics of your setup but you might try installing in a new virtualenv in order to get everything on a single `python` version.

**Comment by firmanhadi** [comment]
Thanks @perrygeo for the suggestion. I will try to install it using virtualenv
