### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag' when install from source

### ISSUE THREAD

**Issue by fireattack** [mapbox/rio-color#62]
```
(v) G:\_temp\!test\rio-color>pip install -e .
Obtaining file:///G:/_temp/%21test/rio-color
Requirement already satisfied: click in g:\_temp\!test\v\lib\site-packages (from rio-color==1.0.0) (7.1.2)
Collecting rasterio>=1.0a11
  Downloading rasterio-1.1.5.tar.gz (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.4 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'g:\_temp\!test\v\scripts\python.exe' 'g:\_temp\!test\v\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Administrator\AppData\Local\Temp\pip-build-env-o8wr7vzf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Program Files\Python37\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "g:\_temp\!test\v\lib\site-packages\pip\__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "g:\_temp\!test\v\lib\site-packages\pip\_internal\cli\main.py", line 5, in <module>
      import locale
    File "C:\Program Files\Python37\lib\locale.py", line 16, in <module>
      import re
    File "C:\Program Files\Python37\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'g:\_temp\!test\v\scripts\python.exe' 'g:\_temp\!test\v\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Administrator\AppData\Local\Temp\pip-build-env-o8wr7vzf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.

(v) G:\_temp\!test\rio-color>
```

**Comment by sgillies** [comment]
@fireattack can you check to see if the `enum34` package is present in your `g:\_temp\!test\v\lib\site-packages` directory? If so, you must remove it (see https://github.com/iterative/dvc/issues/1995).

Also, unless you're experienced with installing rasterio on Windows, it's very unlikely that `pip install -e .` will work. Rasterio has C extension modules, and so you will need a compiler, the GDAL library and its header files, etc. We recommend conda and https://anaconda.org/conda-forge/rasterio for rasterio on Windows. There's no rio-color package on conda-forge, but you can install it using conda's pip command into the same environment.

**Comment by fireattack** [comment]
It's indeed caused by `rasterio`. I will figure out how to install that one properly myself.

Thanks for the reply!
